### ISSUE TITLE
Filter by user counts 0

### ISSUE THREAD

**Issue by eor314** [fathomnet/fathomnet-py#1]
`api.imagescount_by_submitter` and `api.images.find_by_contributors_email` exhibiting weird behavior. When querying by @hohonuuli 's email, they return the 66039 images submitted. When filtering by @BGWoodward 's email, count returns 0 and no AImageDTO objects returned by find.

**Comment by hohonuuli** [comment]
Actually, it's probably working right. I hacked in a a workaround for Ben to display the images as NOAA. Details at https://sharing.clickup.com/t/h/1kaa694/NHEUAL7QJOYV139

**Comment by hohonuuli** [comment]
Try running your search with the _fake_ email: `benjamin.woodward@noaa.gov'`

**Comment by kevinsbarnard** [comment]
> Try running your search with the _fake_ email: `benjamin.woodward@noaa.gov`

Confirmed working.
```python
>>> import fathomnet.api.images
>>> fathomnet.api.images.count_by_submitter('benjamin.woodward@noaa.gov'')
ByContributorCount(contributorsEmail='benjamin.woodward@noaa.gov', count=2866)
>>> fathomnet.api.images.find_by_contributors_email('')
2866
```
