### ISSUE TITLE
Question on how to generate coco dataset

### ISSUE THREAD

**Issue by mi2celis** [fathomnet/fathomnet-py#14]
I am able to generate COCO style json files by using  fathomnet-generate with the option --format coco.

In your Colab tutorial you explain how to use image.to_pascal_voc to generate Pascal_VOC dataset. Is there an equivalent way to generate a COCO dataset?

**Comment by kevinsbarnard** [comment]
The COCO format describes a full dataset, whereas Pascal VOC describes annotations for an image. Therefore, something like `image.to_coco` wouldn't work. 

Check the [fathomnet-generate source](https://github.com/fathomnet/fathomnet-py/blob/main/fathomnet/scripts/fathomnet_generate.py#L196-L269) to get an idea of how the `--format coco` flag works. I wrote a small library ([coco-lib](https://github.com/kevinsbarnard/coco-lib)) with COCO data models as Python dataclasses to facilitate this process.
