### ISSUE TITLE
Query images yields bad request

### ISSUE THREAD

**Issue by eor314** [fathomnet/fathomnet-py#15]
Querying images with GeoImageConstraints returns a bad request to url `ValueError: Bad request: http://fathomnet.org:8080/images/query`.

```
from fathomnet.api import images
from fathomnet.models import GeoImageConstraints

constraints = GeoImageConstraints(
    concept='Actinernus',
    maxLatitude=37.0538,
    minLatitude=36.4458,
    maxLongitude=-121.7805,
    minLongitude=-122.5073,
    startTimestamp='2007-08-02',
    minDepth=1300
)

imgs = images.find(constraints)
```

 It looks like the ROOT of the endpoint manger in [fathomnet/api/__init__.py](https://github.com/fathomnet/fathomnet-py/blob/main/fathomnet/api/__init__.py) needs to be updated?

**Comment by hohonuuli** [comment]
`Actinerus` doesn't return any values, i.e. the HTTP response body is `[]`. @eor314  If you sub in something like: `Nanomia` what happens?

@kevinsbarnard Maybe that the python library just needs to be modified to handle empty return values?

**Comment by hohonuuli** [comment]
Sanity check with a simplified `curl` request:

```bash
curl -X 'POST' \
  'http://fathomnet.org:8080/images/query' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "concept": "Actinerus",
  "offset": 0
}'
[]
```

**Comment by kevinsbarnard** [comment]
Looks like it's returning an error due to the `startTimestamp` format. This is pretty strict on the ISO 8601 formatting... should be something like:
```python
startTimestamp='2007-08-02T00:00:00.000Z'
```

**Comment by kevinsbarnard** [comment]
Two lessons here:
1. The error message from (fathomnet-py) is not very helpful when the HTTP response's status code is in the 400's
2. Timestamp formatting is not forgiving

I'll open an issue to improve each of these.

**Comment by eor314** [comment]
Right on, it was the timestamp format in my case. Thanks for helping with troubleshooting.

Kevin, how did you increase the verbosity on the errors? I think I could have sorted it out with a bit more information.

**Comment by kevinsbarnard** [comment]
There isn't a great way to increase verbosity like you describe, but there's a function in fathomnet-py called `fathomnet.util.debug_format_response`.

In this case I just put a debug print statement where the error was raised:
```python
elif res.status_code < 500:  # User error
    print(debug_format_response(res))
    raise ValueError('Bad request: {} {}'.format(method, url))
```

**Comment by hohonuuli** [comment]
@eor314 Just FYI, the one timestamp to rule them all ... <https://en.wikipedia.org/wiki/ISO_8601>
