### ISSUE TITLE
using fathomnet-generate for getting VOC annotations of specific classes together 

### ISSUE THREAD

**Issue by Sidd1609** [fathomnet/fathomnet-py#19]
Hello, @hohonuuli @eor314 I am trying to generate PASCAL VOC format annotations for certain classes in the dataset and was hoping to see if it is possible using fathomnet-generate. 

Also, do you have an estimate of the total dataset size and do you have complete annotations for the original dataset with all classes in PASCAL VOC?

thank you for your support!

**Comment by hohonuuli** [comment]
@Sidd1609 PASCAL VOC is the default output format, although you can explicitly  pass a [`--format voc` flag](https://github.com/fathomnet/fathomnet-py/blob/main/fathomnet/scripts/fathomnet_generate.py#L372) to `fathomnet_generate.py` too.

**Comment by hohonuuli** [comment]
@Sidd1609 

> Also, do you have an estimate of the total dataset size 

ATM there are 176K localizations on 84K images in FathomNet. 

> and do you have complete annotations for the original dataset with all classes in PASCAL VOC?

Not sure what you're asking here. If you want all annotations in FathomNet as VOC ... yes, you can do that using fathomnet_generate.py

**Comment by Sidd1609** [comment]
@hohonuuli I am looking to download only certain classes and not the entire datasets. Is it possible to download the annotations only for certain classes in the images they are present ?

**Comment by hohonuuli** [comment]
@Sidd1609 You can download specific classes. If you're using the python API you can see all the options using:

```sh
python -m pip install fathomnet
fathomnet-generate -h
```

An example to download all types of Bathochordaeus (and other annotations on the same image as the Bathos ...)

```sh
fathomnet-generate -t fathomnet -c Bathochordaeus -o . -a
```

**Comment by hohonuuli** [comment]
If you're not using python, you run the same query using the [FathomNet API](http://fathomnet.org:8080/swagger-ui#/default/findUsingGet_1) and convert the JSON to Pascal VOC yourself. Example: <https://fathomnet.org/api/images/query?concept=Bathochordaeus&taxProviderName=fathomnet>

**Comment by Sidd1609** [comment]
@hohonuuli Thank you so much!

**Comment by kevinsbarnard** [comment]
Closing this issue as completed. By the way, if you're pulling the image entities via the Python API, you can use [`AImageDTO.to_pascal_voc`](https://fathomnet-py.readthedocs.io/en/v0.6.0/models.html#fathomnet.models.AImageDTO.to_pascal_voc) to encode an image as VOC. This is the method that `fathomnet-generate` calls.
