### ISSUE TITLE
New flags for fathomnet_generate.py

### ISSUE THREAD

**Issue by eor314** [fathomnet/fathomnet-py#2]
Two suggestions for flags for the fathomnet_generate command line tool:

1. Flag to grab all concepts from objects that satisfy other filters. 
2. Filter by image dimensions. This might make it easier to select among the cameras that have been deployed on MBARI ROVs.

**Comment by kevinsbarnard** [comment]
> 1. Flag to grab all concepts from objects that satisfy other filters.

Could you clarify this? There is the `--all` flag to include all concepts from images that were found by the specified filters, if that's what you mean. Or, do you mean something along the lines of "don't filter by any concept, just filter by X Y Z metadata"?

> 2. Filter by image dimensions.

Could you provide an example usage of what you're envisioning? I would caution against using image dimensions as a proxy for camera identity, as the letterbox removal process has produced a wide variety of resolutions.

**Comment by eor314** [comment]
1. The latter: _"don't filter by any concept, just filter by X Y Z metadata"?_
2. Right, I forgot about letter boxing. I was hoping to filter by sensor. There are some overlapping dates for when different cameras were on different ROVs (a la [this list](https://mbari.slack.com/archives/CL0U7KYEN/p1637688145135700) that @hohonuuli furnished on Slack). I suppose holding off on this one is right call and we can think about how to do it later.

**Comment by kevinsbarnard** [comment]
1. Resolved in c278ba5
2. I'll hold off on this.
