### ISSUE TITLE
Fathomnet port 8080 unreachable

### ISSUE THREAD

**Issue by Kmoran1512** [fathomnet/fathomnet-py#21]
When attempting to access fathomnet.api through the pypi package in accordance with the documentation

```python
from fathomnet.api import images, boundingboxes

boundingboxes.find_concepts()
```

Or similarly via `curl`
```sh
curl -X 'POST' 'http://fathomnet.org:8080/images/query' -H 'accept: application/json' 
-H 'Content-Type: application/json' 
-d '{
  "concept": "Actinerus",
  "offset": 0
}'
```

I get a refused connection
`Failed to connect to fathomnet.org port 8080: Connection refused`

Has something changed with the pypi registration? I know the website uses https, is this the issue? Or am I missing something else altogether?

**Comment by kevinsbarnard** [comment]
Hi @Kmoran1512, the FathomNet REST API was temporarily down for server maintenance; back up now.

**Comment by Kmoran1512** [comment]
Thank you, I apologize for the unnecessary issue. 
In the future, is there somewhere maintenance is communicated?

**Comment by hohonuuli** [comment]
@Kmoran1512 We don't currently have a channel to communicate maintenance. Usually the server outage during maintenance is extremely brief and isn't noticed by users
