### ISSUE TITLE
'worms.get_info' does not return AphiaID

### ISSUE THREAD

**Issue by khiyer** [fathomnet/fathomnet-py#25]
The 'worms' package does not return 'AphiaID'. Here's an example:

```
from fathomnet.api import worms
print(worms.get_info( 'Caballeraxine chainanica'))
```

This returns
```
WormsNode(name='Caballeraxine chainanica', rank='Species', apiaId=None, alternateNames=[], children=None)
```

Note that the returned tuple name for *AphiaID* seems to be misspelled as `apiaId`

**Comment by hohonuuli** [comment]
Sanity check: <https://fathomnet.org/worms/taxa/info/Caballeraxine%20chainanica> 

@kevinsbarnard Aș @khiyer noted, there's a typo in [WormsNode:610](https://github.com/fathomnet/fathomnet-py/blob/main/fathomnet/dto.py#L607).  

```diff
-    apiaId: Optional[int] = None
+    aphiaId: Optional[int] = None
```

**Comment by kevinsbarnard** [comment]
Thanks for catching and reporting this, @khiyer! I'll push out a fix today.
