### ISSUE TITLE
Albumentations and imgaug versions

### ISSUE THREAD

**Issue by eor314** [fathomnet/fathomnet-py#8]
When cloning into the tutorial ipynb pip throws an error during dependency installation in the first cell. 

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

Maybe specify versions in pip call to resolve?

**Comment by kevinsbarnard** [comment]
This issue occurs because of incompatible packages required for the notebook. This message will continue to occur but causes no errors downstream.
