### ISSUE TITLE
Plotting error in tutorial CoLab

### ISSUE THREAD

**Issue by eor314** [fathomnet/fathomnet-py#9]
Plotting code in cell 8 spits an error related to coloring the bounding box when running from ipynb cloned from git:

> AttributeError: 'Shell' object has no attribute 'highlighting_style'

Attempting to print information about the image (ie `image.url`) returns the same error. Perhaps related to pip install error in issue #8 .

The bounding box in this instance appears to be misplaced. Concept = Cystocrepis setigera
![Screen Shot 2022-03-16 at 11 50 36 AM](https://user-images.githubusercontent.com/7595531/158665267-473aedd7-7f0e-46f5-88c9-401a09f769a6.png)

**Comment by kevinsbarnard** [comment]
Fixed. OpenCV bounding box rendering changed to PIL ImageDraw
